[build-system]
requires = ["uv_build>=0.8.9,<0.9.0"]
build-backend = "uv_build"

[project]
name = "multicosim-greensight"
version = "0.1.0"
authors = [
    { name = "Quinn Thibeault", email = "quinn.thibeault96@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "multicosim",
]

[tool.uv.build-backend]
module-name = "greensight"

[tool.uv.sources]
multicosim = { git = "https://github.com/cpslab-asu/multicosim", branch = "refactor-protocols" }

[tool.pyright]
venvPath = "."
venv = ".venv"
