[project]
name = "sitl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
imu = [
    "click>=8.2.1",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
